<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * App installs, so a phone or a TV box can be listed and booted the way a
 * browser session already can.
 *
 * The website's device picker reads the Laravel `sessions` table, which an app
 * never writes to. This is the app's equivalent: one row per install, carrying
 * the Sanctum token it signed in with, so "boot this device" can revoke the
 * token rather than only flagging a stream.
 *
 * `uuid` is generated by the app at first launch and is what active_streams
 * stores as its session_id for app playback — the plan's "client session key"
 * (docs/plans/mobile-offline-app.md §4.2). That is why it is a string of the
 * same shape a session id is, and why it is unique per user rather than
 * globally: two accounts on one handset are two devices.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('devices', function (Blueprint $table) {
            $table->id();
            $table->string('uuid', 64);
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();

            // 'android' | 'android_tv' today; iOS has a slot but no build.
            // Kept as a string rather than an enum so adding a platform is a
            // deploy, not a migration.
            $table->string('platform', 32);
            $table->string('name')->nullable();      // "Rio's Tecno Spark"
            $table->string('model')->nullable();     // reported by the OS
            $table->string('app_version', 32)->nullable();

            $table->timestamp('last_seen_at')->nullable();
            $table->timestamp('revoked_at')->nullable();

            // The Sanctum token this install currently holds. Nullable
            // because a device row outlives any single token: sign out,
            // sign back in, same device, new token.
            $table->unsignedBigInteger('personal_access_token_id')->nullable();

            $table->timestamps();

            // One row per (account, install). The same handset signed into
            // two accounts is two devices, and each is capped separately.
            $table->unique(['user_id', 'uuid']);

            // The device list, and the "how many devices are live" count.
            $table->index(['user_id', 'revoked_at', 'last_seen_at']);

            // Token -> device, used on every authenticated request to check
            // whether this install has been booted.
            $table->index('personal_access_token_id');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('devices');
    }
};
