import tokensJson from './tokens.json';

/**
 * The Streamit design system, read off the rendered site.
 *
 * The values live in `tokens.json` beside this file, generated by
 * `design/export-tokens.mjs` — **do not edit either by hand.** Every one of
 * them was read from a real element on a real page at a phone viewport, and
 * `design/tokens.json` records, per token, the exact selector and property it
 * came from. Read that file when you want to know why a value is what it is.
 *
 * A token changes when the website changes, and the way to change one is to
 * change the site and run `npm run tokens:export`. Editing a value here would
 * be the app quietly disagreeing with the thing it is meant to look like —
 * which is what `npm run tokens:check` exists to catch.
 *
 * This wrapper is hand-written and stable: it gives the JSON a name, a type
 * and somewhere to hang this explanation. `app.config.ts` reads the JSON
 * directly instead, because Expo's config loader does not transpile the
 * TypeScript its config imports.
 */
export const tokens = tokensJson;

export type Tokens = typeof tokens;
